[model]
alias  = "ornith-1.0-9b-heretic-mtp"
engine = "llama-atomic"
file   = "Ornith-1.0-9B-heretic-MTP-Q4_K_M.gguf"

[args]
ctx_size     = 131072
n_gpu_layers = 99
flash_attn   = true
load_timeout = 90
mmproj       = "mmproj-Ornith-1.0-9B-heretic-MTP-BF16.gguf"
extra        = [
  "--cache-type-k", "q4_0",
  "--cache-type-v", "q4_0",
  "--spec-type", "draft-mtp",
  "--spec-draft-n-max", "3",
  "--batch-size", "2048",
  "--ubatch-size", "512",
  "--jinja"
]
