[model]
alias  = "qwen3-vl-2b"
engine = "llama-tom"
file   = "Qwen3VL-2B-Instruct-Q4_K_M.gguf"

[args]
ctx_size     = 32768
n_gpu_layers = 99
flash_attn   = true
load_timeout = 60
mmproj       = "mmproj-Qwen3VL-2B-Instruct-F16.gguf"
extra        = [
  "--chat-template", "qwen2vl",
  "--image-min-tokens", "1024",
  "--cache-type-k", "q4_0",
  "--cache-type-v", "q4_0",
  "--batch-size", "2048",
  "--ubatch-size", "512"
]
